version: '3.8'

services:
  chat-room-frontend:
    build: .
    ports:
      - "80:80"
    environment:
      - REACT_APP_BASE_URL=http://localhost:3000/
      - REACT_APP_BASE_WS=ws://localhost:3001
      - PORT=80