version: '3.8'

services:
  chat-room-frontend:
    build: .
    ports:
      - "80:80"
      - "3002:3002"
    environment:
      - BASE_URL=http://localhost:3000/
      - BASE_WS=ws://localhost:3001