version: '3.8'

services:
  chat-room-frontend:
    build: 
      context: .
      args:
        - REACT_APP_BASE_URL=http://localhost:3000/
        - REACT_APP_BASE_WS=ws://localhost:3001
    ports:
      - "80:80"
    environment:
      - PORT=80