const chatRoomConstants = {
  SUBMIT_MESSAGE_REQUEST: 'SUBMIT_MESSAGE_REQUEST',
  SUBMIT_MESSAGE_SUCCESS: 'SUBMIT_MESSAGE_SUCCESS',
  SUBMIT_MESSAGE_FAILURE: 'SUBMIT_MESSAGE_FAILURE',

  GET_CONVERSATION_REQUEST: 'GET_CONVERSATION_REQUEST',
  GET_CONVERSATION_SUCCESS: 'GET_CONVERSATION_SUCCESS',
  GET_CONVERSATION_FAILURE: 'GET_CONVERSATION_FAILURE',
  CLEAR_CONVERSATION: 'CLEAR_CONVERSATION',

  UPDATE_CONVERSATION_REQUEST: 'UPDATE_CONVERSATION_REQUEST',
  UPDATE_CONVERSATION_SUCCESS: 'UPDATE_CONVERSATION_SUCCESS',
  UPDATE_CONVERSATION_FAILURE: 'UPDATE_CONVERSATION_FAILURE',
};

export default chatRoomConstants;
