version: "3.4"
services:
  chatroomfrontend:
    container_name: chatroomfrontend
    image: chatroomfrontend
    restart: unless-stopped
    build: ./frontend
    ports:
      - "80:80"
    links:
      - chatroombackend
    depends_on:
      - chatroombackend
    environment:
      NODE_ENV: production
      REACT_APP_BASE_URL: http://localhost:3000/
      REACT_APP_BASE_WS: ws://localhost:3001
      PORT: 80
  chatroombackend:
    container_name: chatroombackend
    image: chatroombackend
    restart: unless-stopped
    build: ./backend
    ports:
      - "3000:3000"
      - "3001:3001"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      NODE_ENV: production
      JWT_SECRET_KEY: '@CHATROOMBACKEND'
      DATABASE_URL: mongodb://mongo:27017/db_name
      PORT: 3000
      WSS_PORT: 3001
      CORS_URL: '*'
  mongo:
    container_name: mongo
    restart: unless-stopped
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/mongo
volumes:
  dbdata:
