version: "3.4"
services:
  chatroomfrontend:
    build: 
      context: ./frontend
      args:
        - REACT_APP_BASE_URL=http://localhost:3000/
        - REACT_APP_BASE_WS=ws://localhost:3001
    ports:
      - "80:80"
    links:
      - chatroombackend
    depends_on:
      - chatroombackend
    environment:
      NODE_ENV: production
      PORT: 80
  chatroombackend:
    build: ./backend
    ports:
      - "3000:3000"
      - "3001:3001"
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      NODE_ENV: production
      JWT_SECRET_KEY: '@CHATROOMBACKEND'
      DATABASE_URL: mongodb://mongodb:27017/dbname
      PORT: 3000
      WSS_PORT: 3001
      CORS_URL: '*'
  
  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
