version: '3.8'

services:
  chat-room-backend:
    build: .
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mongodb://mongodb:27017/mydatabase
      - JWT_SECRET_KEY=@CHATROOMBACKEND
      - PORT=3000
      - WSS_PORT=3001
      - CORS_URL=*

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
