version: "3.4"
services:
  chatroomfrontend:
    container_name: chatroomfrontend
    image: chatroomfrontend
    restart: unless-stopped
    build: ./../frontend
    ports:
      - "80:80"
    links:
      - demochatroom
    depends_on:
      - demochatroom
    environment:
      NODE_ENV: production
      BASE_URL: <to-be-defined>
      BASE_WS: ws://<to-be-defined>:3001
  chatroombackend:
    container_name: chatroombackend
    image: chatroombackend
    restart: unless-stopped
    build: ./../backend
    ports:
      - "3000:3000"
      - "3001:3001"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      DATABASE_URL: mongodb://mongo:27017/db_name
  mongo:
    container_name: mongo
    restart: unless-stopped
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/mongo
volumes:
  dbdata:
